// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for blogpost documents */
interface BlogpostDocumentData {
    /**
     * publishedDate field in *blogpost*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.publisheddate
     * - **Tab**: Publication
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    publisheddate: prismicT.DateField;
    /**
     * title field in *blogpost*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.title
     * - **Tab**: Publication
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * paragraph field in *blogpost*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.paragraph
     * - **Tab**: Publication
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    paragraph: prismicT.KeyTextField;
    /**
     * image field in *blogpost*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.image
     * - **Tab**: Publication
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * postDescription field in *blogpost*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.postdescription
     * - **Tab**: Publication
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    postdescription: prismicT.KeyTextField;
}
/**
 * blogpost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogpostDocumentData>, "blogpost", Lang>;
export type AllDocumentTypes = BlogpostDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BlogpostDocumentData, BlogpostDocument, AllDocumentTypes };
    }
}
